### ISSUE TITLE
CTD with versions 1.16.6+

### ISSUE THREAD

**Issue by LT-Rascek** [dguenms/Dawn-of-Civilization#356]
Running on Steam version of Civ4 with later mod versions.
Loads fine, but CTD occurs when attempting to set up the game after selecting civilization and options.
Probably associated with the change to python script instead of scenario maps?

If additional information is required (such as Python logs), please let me know which I should furnish and what settings should be set in the *.ini to dump the necessary data.

**Comment by dguenms** [comment]
Thank you for the report. A fix for this issue has been pushed after the v1.16.7 release, so you can try to use the latest git version. Otherwise, please wait for the v1.16.8 release, which hopefully happens soon.

If you have further feedback or for future reports, please use the forums at https://forums.civfanatics.com/forums/rhyes-and-fall-dawn-of-civilization.452/
