### ISSUE TITLE
Ships finish turn after unloading

### ISSUE THREAD

**Issue by dguenms** [dguenms/Dawn-of-Civilization#4]
Even if some moves are left on a naval transport, they finish their turn after unloading units (or ordered to enter a land tile), instead of awaiting further orders.

**Comment by temujin2k** [comment]
Well, in my case, they "finish their turn" but the remaining moves do not get consumed. They enter the "go to sleep" mode instead. You have to activate them again to give them orders.

**Comment by dguenms** [comment]
True. Should have worded it better.

**Comment by temujin2k** [comment]
It's okay, though. It does not look like a bug to me, but it's really a hassle to reactivate the ship by clicking. Since it's been very long since I last played vanilla BTS, I'm not pretty sure if the same behavior can be observed there.

(Erratum: It's not "go to sleep" mode; it's actually "skip turn" mode, since it would be active and ready for orders again the next turn. Sorry, my bad!)

**Comment by dguenms** [comment]
I regard that as a bug since it is not the intended behavior.
