### ISSUE TITLE
Support for Civilization IV under Mac OS X?

### ISSUE THREAD

**Issue by hanfeisun** [dguenms/Dawn-of-Civilization#51]
The Civilization IV on my machine is installed by Steam under Mac OS X.  

I am not sure whether DoC will work  on Mac OSX.  But from this thread (http://forums.civlovers.com/showthread.php?t=227093), it seems that there are some issues about `CvGameCoreDLL` on Mac.

Does DoC support mac version of Civ4 currently? If so, would it be possible to get any instructions about how to install DoC on mac?

**Comment by MeuhV1** [comment]
No. DoC has a custom CvGameCoreDLL. All mods with a custom CvGameCoreDLL do not work on Mac OS X..

**Comment by hanfeisun** [comment]
Thanks! Is there any source code for that CvGameCoreDLL? Is it possible to compile the binary CvGameCoreDLL from source code?

**Comment by MeuhV1** [comment]
They are in the CvGameCoreDLL-folder in files section
https://github.com/dguenms/Dawn-of-Civilization/tree/develop/CvGameCoreDLL

**Comment by dguenms** [comment]
MeuhV1 is right. For Windows, Firaxis bundled some of the C++ code into the DLL so that we could recompile it to change things. Unfortunately, for Mac, everything is directly coded into the executable and cannot be changed. DoC relies heavily on DLL changes so a Mac port is not feasible.

The source code for the DLL is included in this repository (CvGameCoreDLL directory). You can change and compile it yourself of course, it works the same way as compiling any Civ4 DLL. You can find guides on how to do that on Civfanatics.

**Comment by hanfeisun** [comment]
@dguenms 

Thanks so much! I found there is a `CvGameCoreDLL.dll` file whose absolute path is `~/Library/Application\ Support/Steam/steamapps/common/Sid\ Meier\'s\ Civilization\ IV\ Beyond\ the\ Sword/Assets/CvGameCoreDLL.dll`.  (screenshot attached below)

<img width="830" alt="screen shot 2015-12-31 at 8 34 13 pm" src="https://cloud.githubusercontent.com/assets/922081/12064439/0dac3cb0-affe-11e5-91d2-6b0406ef69f3.png">

I'm not sure whether this `CvGameCoreDLL` could be overwritten by the one of DoC.. If it could be overwritten, does that mean DoC could run on Mac...

**Comment by dguenms** [comment]
I don't know why that DLL exists in your Mac installation, but I don't think it is used. The DoC mod directory has its own DLL that is used instead of the default one in the BtS folder, but it won't have any effect on a Mac system.

**Comment by hanfeisun** [comment]
I see. Maybe it was copied from another place which I can't remember.. It looks that playing Civ4 on window is the only way to play DoC.. Thanks.
